// Define column configurations per resource type
// Each entry is an array of paths to extract values from
type ColumnConfig = {
  header: string;
  path: string; // Simple dot-separated path (e.g., "name.0.family", "subject.reference")
};

export const RESOURCE_COLUMNS: Record<string, ColumnConfig[]> = {
  Patient: [
    { header: "ID", path: "id" },
    { header: "Name", path: "name.family" },
    { header: "Identifier", path: "identifier.value" },
    { header: "Given Name", path: "name.given" },
    { header: "Gender", path: "gender" },
    { header: "Birth Date", path: "birthDate" },
  ],
  Observation: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Code", path: "code.text" },
    { header: "Value", path: "valueQuantity.value" },
    { header: "Subject", path: "subject.reference" },
  ],
  Encounter: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Class", path: "class.code" },
    { header: "Subject", path: "subject.reference" },
    { header: "Period", path: "period.start" },
  ],
  Condition: [
    { header: "ID", path: "id" },
    { header: "Code", path: "code.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Onset", path: "onsetDateTime" },
    { header: "Status", path: "clinicalStatus.coding.code" },
  ],
  MedicationRequest: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Medication", path: "medicationCodeableConcept.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Intent", path: "intent" },
  ],
  Practitioner: [
    { header: "ID", path: "id" },
    { header: "Name", path: "name.family" },
    { header: "Given Name", path: "name.given" },
  ],
  Organization: [
    { header: "ID", path: "id" },
    { header: "Name", path: "name" },
  ],
  DiagnosticReport: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Code", path: "code.text" },
    { header: "Subject", path: "subject.reference" },
  ],
  Procedure: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Code", path: "code.text" },
    { header: "Subject", path: "subject.reference" },
  ],
  Appointment: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Start", path: "start" },
  ],
  Account: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Period", path: "servicePeriod.start" },
  ],
  AllergyIntolerance: [
    { header: "ID", path: "id" },
    { header: "Clinical Status", path: "clinicalStatus.coding.code" },
    { header: "Code", path: "code.text" },
    { header: "Patient", path: "patient.reference" },
    { header: "Onset", path: "onsetDateTime" },
  ],
  AppointmentResponse: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Appointment", path: "appointment.reference" },
    { header: "Actor", path: "actor.reference" },
  ],
  AuditEvent: [
    { header: "ID", path: "id" },
    { header: "Type", path: "type.code" },
    { header: "Action", path: "action" },
    { header: "Recorded", path: "recorded" },
  ],
  Bundle: [
    { header: "ID", path: "id" },
    { header: "Type", path: "type" },
    { header: "Timestamp", path: "timestamp" },
  ],
  CapabilityStatement: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Kind", path: "kind" },
    { header: "FHIR Version", path: "fhirVersion" },
  ],
  CarePlan: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Intent", path: "intent" },
    { header: "Subject", path: "subject.reference" },
    { header: "Period", path: "period.start" },
  ],
  CareTeam: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "Subject", path: "subject.reference" },
  ],
  Claim: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type.text" },
    { header: "Patient", path: "patient.reference" },
    { header: "Created", path: "created" },
  ],
  ClaimResponse: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type.text" },
    { header: "Patient", path: "patient.reference" },
    { header: "Created", path: "created" },
  ],
  ClinicalImpression: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Subject", path: "subject.reference" },
    { header: "Date", path: "date" },
  ],
  CodeSystem: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "URL", path: "url" },
  ],
  Communication: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Category", path: "category.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Sent", path: "sent" },
  ],
  CommunicationRequest: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Subject", path: "subject.reference" },
    { header: "Authored On", path: "authoredOn" },
  ],
  Composition: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Date", path: "date" },
  ],
  ConceptMap: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "URL", path: "url" },
  ],
  Consent: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Scope", path: "scope.text" },
    { header: "Patient", path: "patient.reference" },
    { header: "Date Time", path: "dateTime" },
  ],
  Contract: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Subject", path: "subject.reference" },
    { header: "Issued", path: "issued" },
  ],
  Coverage: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Beneficiary", path: "beneficiary.reference" },
    { header: "Period", path: "period.start" },
  ],
  Device: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Device Name", path: "deviceName.name" },
    { header: "Manufacturer", path: "manufacturer" },
  ],
  DeviceRequest: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Code", path: "code.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Authored On", path: "authoredOn" },
  ],
  DocumentReference: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Date", path: "date" },
  ],
  EpisodeOfCare: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Patient", path: "patient.reference" },
    { header: "Period", path: "period.start" },
  ],
  ExplanationOfBenefit: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Patient", path: "patient.reference" },
    { header: "Created", path: "created" },
  ],
  FamilyMemberHistory: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Patient", path: "patient.reference" },
    { header: "Date", path: "date" },
  ],
  Flag: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Code", path: "code.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Period", path: "period.start" },
  ],
  Goal: [
    { header: "ID", path: "id" },
    { header: "Status", path: "lifecycleStatus" },
    { header: "Subject", path: "subject.reference" },
    { header: "Start Date", path: "startDate" },
  ],
  Group: [
    { header: "ID", path: "id" },
    { header: "Type", path: "type" },
    { header: "Name", path: "name" },
    { header: "Quantity", path: "quantity" },
  ],
  HealthcareService: [
    { header: "ID", path: "id" },
    { header: "Name", path: "name" },
    { header: "Category", path: "category.text" },
    { header: "Provided By", path: "providedBy.reference" },
  ],
  ImagingStudy: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Subject", path: "subject.reference" },
    { header: "Started", path: "started" },
  ],
  Immunization: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Vaccine Code", path: "vaccineCode.text" },
    { header: "Patient", path: "patient.reference" },
    { header: "Occurrence", path: "occurrenceDateTime" },
  ],
  Invoice: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Date", path: "date" },
  ],
  List: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Mode", path: "mode" },
    { header: "Title", path: "title" },
    { header: "Date", path: "date" },
  ],
  Location: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "Address", path: "address.text" },
  ],
  Measure: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "URL", path: "url" },
  ],
  MeasureReport: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type" },
    { header: "Measure", path: "measure.reference" },
    { header: "Date", path: "date" },
  ],
  Medication: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Code", path: "code.text" },
    { header: "Manufacturer", path: "manufacturer.reference" },
  ],
  MedicationAdministration: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Medication", path: "medicationCodeableConcept.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Effective", path: "effectiveDateTime" },
  ],
  MedicationDispense: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Medication", path: "medicationCodeableConcept.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "When Prepared", path: "whenPrepared" },
  ],
  MedicationStatement: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Medication", path: "medicationCodeableConcept.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Effective", path: "effectiveDateTime" },
  ],
  MessageHeader: [
    { header: "ID", path: "id" },
    { header: "Event", path: "event.code" },
    { header: "Source", path: "source.name" },
    { header: "Timestamp", path: "timestamp" },
  ],
  NamingSystem: [
    { header: "ID", path: "id" },
    { header: "Name", path: "name" },
    { header: "Kind", path: "kind" },
    { header: "Date", path: "date" },
  ],
  OperationDefinition: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "URL", path: "url" },
  ],
  OperationOutcome: [
    { header: "ID", path: "id" },
    { header: "Severity", path: "issue.severity" },
    { header: "Code", path: "issue.code" },
  ],
  OrganizationAffiliation: [
    { header: "ID", path: "id" },
    { header: "Organization", path: "organization.reference" },
    { header: "Participating", path: "participatingOrganization.reference" },
    { header: "Period", path: "period.start" },
  ],
  Person: [
    { header: "ID", path: "id" },
    { header: "Name", path: "name.family" },
    { header: "Gender", path: "gender" },
    { header: "Birth Date", path: "birthDate" },
  ],
  PlanDefinition: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Title", path: "title" },
    { header: "Date", path: "date" },
  ],
  PractitionerRole: [
    { header: "ID", path: "id" },
    { header: "Practitioner", path: "practitioner.reference" },
    { header: "Organization", path: "organization.reference" },
    { header: "Period", path: "period.start" },
  ],
  Provenance: [
    { header: "ID", path: "id" },
    { header: "Recorded", path: "recorded" },
    { header: "Target", path: "target.reference" },
    { header: "Activity", path: "activity.text" },
  ],
  Questionnaire: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Title", path: "title" },
    { header: "URL", path: "url" },
  ],
  QuestionnaireResponse: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Subject", path: "subject.reference" },
    { header: "Authored", path: "authored" },
  ],
  RelatedPerson: [
    { header: "ID", path: "id" },
    { header: "Patient", path: "patient.reference" },
    { header: "Relationship", path: "relationship.text" },
    { header: "Name", path: "name.family" },
  ],
  ResearchStudy: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Title", path: "title" },
    { header: "Period", path: "period.start" },
  ],
  RiskAssessment: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Subject", path: "subject.reference" },
    { header: "Occurrence", path: "occurrenceDateTime" },
  ],
  Schedule: [
    { header: "ID", path: "id" },
    { header: "Active", path: "active" },
    { header: "Service Type", path: "serviceType.text" },
    { header: "Actor", path: "actor.reference" },
    { header: "Planning Horizon", path: "planningHorizon.start" },
  ],
  SearchParameter: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "Code", path: "code" },
    { header: "Base", path: "base" },
  ],
  ServiceRequest: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Intent", path: "intent" },
    { header: "Code", path: "code.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Authored On", path: "authoredOn" },
  ],
  Slot: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Schedule", path: "schedule.reference" },
    { header: "Start", path: "start" },
    { header: "End", path: "end" },
  ],
  Specimen: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Type", path: "type.text" },
    { header: "Subject", path: "subject.reference" },
    { header: "Collected", path: "collectedDateTime" },
  ],
  StructureDefinition: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "URL", path: "url" },
    { header: "Kind", path: "kind" },
  ],
  Subscription: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Criteria", path: "criteria" },
    { header: "Channel Type", path: "channel.type" },
  ],
  Substance: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Code", path: "code.text" },
    { header: "Category", path: "category.text" },
  ],
  SupplyDelivery: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Patient", path: "patient.reference" },
    { header: "Supplied Item", path: "suppliedItem.itemCodeableConcept.text" },
    { header: "Occurrence", path: "occurrenceDateTime" },
  ],
  SupplyRequest: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Category", path: "category.text" },
    { header: "Priority", path: "priority" },
    { header: "Item", path: "itemCodeableConcept.text" },
    { header: "Occurrence", path: "occurrenceDateTime" },
  ],
  Task: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Intent", path: "intent" },
    { header: "For", path: "for.reference" },
    { header: "Authored On", path: "authoredOn" },
  ],
  ValueSet: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Name", path: "name" },
    { header: "URL", path: "url" },
  ],
  VisionPrescription: [
    { header: "ID", path: "id" },
    { header: "Status", path: "status" },
    { header: "Patient", path: "patient.reference" },
    { header: "Date Written", path: "dateWritten" },
  ],
};
